var searchData=
[
  ['f2c_5fcomm_72',['f2c_comm',['../interface_8cpp.html#a499593baacfebeddb2676f4999e88f4b',1,'f2c_comm(MPI_Fint *Fcomm):&#160;interface.cpp'],['../interface__old_8cpp.html#a7b6e16d450fa4359026674afd0d4ae33',1,'f2c_comm(int *Fcomm):&#160;interface_old.cpp']]],
  ['f_5fdriver_5fksdft_2ef90_73',['f_driver_ksdft.f90',['../f__driver__ksdft_8f90.html',1,'']]],
  ['f_5fdriver_5fpselinv_5fcomplex_2ef90_74',['f_driver_pselinv_complex.f90',['../f__driver__pselinv__complex_8f90.html',1,'']]],
  ['f_5fdriver_5fpselinv_5fcomplex_5funsym_2ef90_75',['f_driver_pselinv_complex_unsym.f90',['../f__driver__pselinv__complex__unsym_8f90.html',1,'']]],
  ['f_5fdriver_5fpselinv_5freal_2ef90_76',['f_driver_pselinv_real.f90',['../f__driver__pselinv__real_8f90.html',1,'']]],
  ['f_5fdriver_5fpselinv_5freal_5funsym_2ef90_77',['f_driver_pselinv_real_unsym.f90',['../f__driver__pselinv__real__unsym_8f90.html',1,'']]],
  ['f_5fget_5fpole_5fdm_78',['f_get_pole_dm',['../interfacef__ppexsi__interface_1_1f__get__pole__dm.html',1,'f_ppexsi_interface']]],
  ['f_5fget_5fpole_5fedm_79',['f_get_pole_edm',['../interfacef__ppexsi__interface_1_1f__get__pole__edm.html',1,'f_ppexsi_interface']]],
  ['f_5fget_5fpole_5ffdm_80',['f_get_pole_fdm',['../interfacef__ppexsi__interface_1_1f__get__pole__fdm.html',1,'f_ppexsi_interface']]],
  ['f_5finterface_2ef90_81',['f_interface.f90',['../f__interface_8f90.html',1,'']]],
  ['f_5fpara_5fread_5fdistsparsematrix_82',['f_para_read_distsparsematrix',['../interfacef__ppexsi__interface_1_1f__para__read__distsparsematrix.html',1,'f_ppexsi_interface::f_para_read_distsparsematrix'],['../interface_8cpp.html#a766ca83aea76e08650c66a5f80ed3a8a',1,'f_para_read_distsparsematrix(char *filename, int size, int nnz, int nnzLocal, int numColLocal, int *colptrLocal, int *rowindLocal, double *nzvalLocal, MPI_Fint *Fcomm):&#160;interface.cpp'],['../interface__old_8cpp.html#a2dbc8ca32653a859df48fc7d2f1ff5e1',1,'f_para_read_distsparsematrix(char *filename, int *size, int *nnz, int *nnzLocal, int *numColLocal, int *colptrLocal, int *rowindLocal, double *nzvalLocal, int *Fcomm):&#160;interface_old.cpp']]],
  ['f_5fppexsi_5fcalculate_5fedm_5fcorrection_5fcomplex_83',['f_ppexsi_calculate_edm_correction_complex',['../interfacef__ppexsi__interface_1_1f__ppexsi__calculate__edm__correction__complex.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fcalculate_5fedm_5fcorrection_5freal_84',['f_ppexsi_calculate_edm_correction_real',['../interfacef__ppexsi__interface_1_1f__ppexsi__calculate__edm__correction__real.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fcalculate_5ffermi_5foperator_5fcomplex_85',['f_ppexsi_calculate_fermi_operator_complex',['../interfacef__ppexsi__interface_1_1f__ppexsi__calculate__fermi__operator__complex.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fcalculate_5ffermi_5foperator_5freal_86',['f_ppexsi_calculate_fermi_operator_real',['../interfacef__ppexsi__interface_1_1f__ppexsi__calculate__fermi__operator__real.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fcalculate_5ffermi_5foperator_5freal3_87',['f_ppexsi_calculate_fermi_operator_real3',['../interfacef__ppexsi__interface_1_1f__ppexsi__calculate__fermi__operator__real3.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fdft_5fdriver_88',['f_ppexsi_dft_driver',['../interfacef__ppexsi__interface_1_1f__ppexsi__dft__driver.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fdft_5fdriver2_89',['f_ppexsi_dft_driver2',['../interfacef__ppexsi__interface_1_1f__ppexsi__dft__driver2.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fdft_5fdriver2_5fdeprecate_90',['f_ppexsi_dft_driver2_deprecate',['../interfacef__ppexsi__interface_1_1f__ppexsi__dft__driver2__deprecate.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5finertia_5fcount_5fcomplex_5fmatrix_91',['f_ppexsi_inertia_count_complex_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__inertia__count__complex__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5finertia_5fcount_5freal_5fmatrix_92',['f_ppexsi_inertia_count_real_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__inertia__count__real__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5finertiacount_5finterface_93',['f_ppexsi_inertiacount_interface',['../interface__old_8cpp.html#aa00635c5c0692cdb1947d32109a5af61',1,'interface_old.cpp']]],
  ['f_5fppexsi_5finterpolate_5fdm_5fcomplex_94',['f_ppexsi_interpolate_dm_complex',['../interfacef__ppexsi__interface_1_1f__ppexsi__interpolate__dm__complex.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5finterpolate_5fdm_5freal_95',['f_ppexsi_interpolate_dm_real',['../interfacef__ppexsi__interface_1_1f__ppexsi__interpolate__dm__real.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fload_5fcomplex_5fhs_5fmatrix_96',['f_ppexsi_load_complex_hs_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__load__complex__hs__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fload_5freal_5fhs_5fmatrix_97',['f_ppexsi_load_real_hs_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__load__real__hs__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5flocaldos_5finterface_98',['f_ppexsi_localdos_interface',['../interface__old_8cpp.html#ac55212d9a2397cf7de995b980f85222c',1,'interface_old.cpp']]],
  ['f_5fppexsi_5foptions_99',['f_ppexsi_options',['../structf__ppexsi__interface_1_1f__ppexsi__options.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fplan_5ffinalize_100',['f_ppexsi_plan_finalize',['../interfacef__ppexsi__interface_1_1f__ppexsi__plan__finalize.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fplan_5finitialize_101',['f_ppexsi_plan_initialize',['../interfacef__ppexsi__interface_1_1f__ppexsi__plan__initialize.html',1,'f_ppexsi_interface::f_ppexsi_plan_initialize'],['../interface_8cpp.html#adb19a8330133d748c40b93dd1fe9d65a',1,'f_ppexsi_plan_initialize():&#160;interface.cpp']]],
  ['f_5fppexsi_5fraw_5finertiacount_5finterface_102',['f_ppexsi_raw_inertiacount_interface',['../interface__old_8cpp.html#a85f48078e2ac1559a25fcbec01a3ce97',1,'interface_old.cpp']]],
  ['f_5fppexsi_5fretrieve_5fcomplex_5fdft_5fmatrix_103',['f_ppexsi_retrieve_complex_dft_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__retrieve__complex__dft__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fretrieve_5fcomplex_5fdm_104',['f_ppexsi_retrieve_complex_dm',['../interfacef__ppexsi__interface_1_1f__ppexsi__retrieve__complex__dm.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fretrieve_5fcomplex_5fedm_105',['f_ppexsi_retrieve_complex_edm',['../interfacef__ppexsi__interface_1_1f__ppexsi__retrieve__complex__edm.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fretrieve_5fcomplex_5ffdm_106',['f_ppexsi_retrieve_complex_fdm',['../interfacef__ppexsi__interface_1_1f__ppexsi__retrieve__complex__fdm.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fretrieve_5freal_5fdft_5fmatrix_107',['f_ppexsi_retrieve_real_dft_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__retrieve__real__dft__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fretrieve_5freal_5fdm_108',['f_ppexsi_retrieve_real_dm',['../interfacef__ppexsi__interface_1_1f__ppexsi__retrieve__real__dm.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fretrieve_5freal_5fedm_109',['f_ppexsi_retrieve_real_edm',['../interfacef__ppexsi__interface_1_1f__ppexsi__retrieve__real__edm.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fretrieve_5freal_5ffdm_110',['f_ppexsi_retrieve_real_fdm',['../interfacef__ppexsi__interface_1_1f__ppexsi__retrieve__real__fdm.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fselinv_5fcomplex_5fsymmetric_5fmatrix_111',['f_ppexsi_selinv_complex_symmetric_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__selinv__complex__symmetric__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fselinv_5fcomplex_5funsymmetric_5fmatrix_112',['f_ppexsi_selinv_complex_unsymmetric_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__selinv__complex__unsymmetric__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fselinv_5finterface_113',['f_ppexsi_selinv_interface',['../interface__old_8cpp.html#a15efc9c2b7fc06763a923d6f8391b786',1,'interface_old.cpp']]],
  ['f_5fppexsi_5fselinv_5freal_5fsymmetric_5fmatrix_114',['f_ppexsi_selinv_real_symmetric_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__selinv__real__symmetric__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fselinv_5freal_5funsymmetric_5fmatrix_115',['f_ppexsi_selinv_real_unsymmetric_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__selinv__real__unsymmetric__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fset_5fdefault_5foptions_116',['f_ppexsi_set_default_options',['../interfacef__ppexsi__interface_1_1f__ppexsi__set__default__options.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fsolve_5finterface_117',['f_ppexsi_solve_interface',['../interface__old_8cpp.html#aa9bb6ccfca6480123bb79e0cda0eb5e6',1,'interface_old.cpp']]],
  ['f_5fppexsi_5fsymbolic_5ffactorize_5fcomplex_5fsymmetric_5fmatrix_118',['f_ppexsi_symbolic_factorize_complex_symmetric_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__symbolic__factorize__complex__symmetric__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fsymbolic_5ffactorize_5fcomplex_5funsymmetric_5fmatrix_119',['f_ppexsi_symbolic_factorize_complex_unsymmetric_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__symbolic__factorize__complex__unsymmetric__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fsymbolic_5ffactorize_5freal_5fsymmetric_5fmatrix_120',['f_ppexsi_symbolic_factorize_real_symmetric_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__symbolic__factorize__real__symmetric__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fppexsi_5fsymbolic_5ffactorize_5freal_5funsymmetric_5fmatrix_121',['f_ppexsi_symbolic_factorize_real_unsymmetric_matrix',['../interfacef__ppexsi__interface_1_1f__ppexsi__symbolic__factorize__real__unsymmetric__matrix.html',1,'f_ppexsi_interface']]],
  ['f_5fpselinv_5fcomplex_5fsymmetric_5finterface_122',['f_pselinv_complex_symmetric_interface',['../interface__old_8cpp.html#af4902132f0b53d8e87c92c0c3cc9ded2',1,'interface_old.cpp']]],
  ['f_5fread_5fdistsparsematrix_5fformatted_123',['f_read_distsparsematrix_formatted',['../interfacef__ppexsi__interface_1_1f__read__distsparsematrix__formatted.html',1,'f_ppexsi_interface::f_read_distsparsematrix_formatted'],['../interface_8cpp.html#aebdce1b0ac61eb39b0d211dc63ce0c1f',1,'f_read_distsparsematrix_formatted(char *filename, int size, int nnz, int nnzLocal, int numColLocal, int *colptrLocal, int *rowindLocal, double *nzvalLocal, MPI_Fint *Fcomm):&#160;interface.cpp'],['../interface__old_8cpp.html#ab5e71ac6a85f01573a00fd4405e9832d',1,'f_read_distsparsematrix_formatted(char *filename, int *size, int *nnz, int *nnzLocal, int *numColLocal, int *colptrLocal, int *rowindLocal, double *nzvalLocal, int *Fcomm):&#160;interface_old.cpp']]],
  ['f_5fread_5fdistsparsematrix_5fformatted_5fhead_124',['f_read_distsparsematrix_formatted_head',['../interfacef__ppexsi__interface_1_1f__read__distsparsematrix__formatted__head.html',1,'f_ppexsi_interface::f_read_distsparsematrix_formatted_head'],['../interface_8cpp.html#a6bc52c9e70ee43fe53cc5e28fd9dd444',1,'f_read_distsparsematrix_formatted_head(char *filename, int *size, int *nnz, int *nnzLocal, int *numColLocal, MPI_Fint *Fcomm):&#160;interface.cpp'],['../interface__old_8cpp.html#ab4d29f3647207fb711d444dae4311160',1,'f_read_distsparsematrix_formatted_head(char *filename, int *size, int *nnz, int *nnzLocal, int *numColLocal, int *Fcomm):&#160;interface_old.cpp']]],
  ['f_5fread_5fdistsparsematrix_5fhead_125',['f_read_distsparsematrix_head',['../interfacef__ppexsi__interface_1_1f__read__distsparsematrix__head.html',1,'f_ppexsi_interface::f_read_distsparsematrix_head'],['../interface_8cpp.html#a2a064bdd4bad0a0c658f2aa2a05ce1d7',1,'f_read_distsparsematrix_head(char *filename, int *size, int *nnz, int *nnzLocal, int *numColLocal, MPI_Fint *Fcomm):&#160;interface.cpp'],['../interface__old_8cpp.html#a35d35dadc6fa1d0cf2fc4693871326be',1,'f_read_distsparsematrix_head(char *filename, int *size, int *nnz, int *nnzLocal, int *numColLocal, int *Fcomm):&#160;interface_old.cpp']]],
  ['factorizationoptions_126',['FactorizationOptions',['../struct_p_e_x_s_i_1_1_factorization_options.html',1,'PEXSI']]],
  ['firstblockcol_127',['FirstBlockCol',['../namespace_p_e_x_s_i.html#a012c82c2f9bffdc6e74674bd67475a00',1,'PEXSI']]],
  ['firstblockrow_128',['FirstBlockRow',['../namespace_p_e_x_s_i.html#a2f59a2c8f7a04fc510f1ea2980258001',1,'PEXSI']]],
  ['flops_2ehpp_129',['flops.hpp',['../flops_8hpp.html',1,'']]],
  ['freeenergydensityrealmat_130',['FreeEnergyDensityRealMat',['../class_p_e_x_s_i_1_1_p_p_e_x_s_i_data.html#a136cd30bdca8b6cb68ac3bb6eb8bef40',1,'PEXSI::PPEXSIData']]],
  ['ftreebcast_131',['FTreeBcast',['../class_p_e_x_s_i_1_1_f_tree_bcast.html',1,'PEXSI']]],
  ['ftreebcast2_132',['FTreeBcast2',['../class_p_e_x_s_i_1_1_f_tree_bcast2.html',1,'PEXSI']]],
  ['ftreereduce_133',['FTreeReduce',['../class_p_e_x_s_i_1_1_f_tree_reduce.html',1,'PEXSI']]],
  ['ftreereduce_5fv2_134',['FTreeReduce_v2',['../class_p_e_x_s_i_1_1_f_tree_reduce__v2.html',1,'PEXSI']]],
  ['function_5ftimer_135',['function_timer',['../classfunction__timer.html',1,'']]]
];
